const categories = [
  {
    category: "Financial Services & Business Advisory",
    subcategories: [
      "Investment Advisors / Portfolio Managers",
      "Chartered Accountants / Tax Consultants",
      "Financial Planners / Wealth Managers",
      "Loan Consultants / Mortgage Brokers",
      "Insurance (Life / Health / General)",
      "Business Valuation Experts",
      "Forex / International Remittance",
      "Virtual CFO / Financial Modelling",
      "Other",
    ],
  },
  {
    category: "Legal, Compliance & Corporate Services",
    subcategories: [
      "Corporate Lawyers / Legal Advisors",
      "Intellectual Property Consultants",
      "Company Secretaries",
      "Labor Law / Industrial Law Experts",
      "Government Liaison Consultants (Licensing/Permits)",
      "Compliance & Risk Management",
      "Other",
    ],
  },
  {
    category: "Marketing, Media & Branding",
    subcategories: [
      "Digital Marketing Agencies",
      "SEO / SEM Experts",
      "Social Media Managers",
      "Advertising & Creative Agencies",
      "Brand Strategists",
      "Influencers / Anchors / Image Consultants",
      "Content Writers / Copywriters / Bloggers",
      "Video Production / Photographers",
      "Event Management Companies",
      "PR Consultants",
      "Other",
    ],
  },
  {
    category: "IT, Software & Technology",
    subcategories: [
      "Website Developers",
      "App Developers (iOS/Android)",
      "ERP / CRM Consultants",
      "Custom Software Solutions",
      "AI / ML Specialists",
      "Cybersecurity Experts",
      "Cloud & Hosting Services",
      "Tech Product Startups",
      "UI/UX Designers",
      "Blockchain / Web3 Experts",
      "Other",
    ],
  },
  {
    category: "Health, Wellness & Medical",
    subcategories: [
      "General Physicians / Specialists",
      "Dentists / Skin Clinics",
      "Alternative Therapy (Homeopathy, Ayurveda, Naturopathy)",
      "Physiotherapists / Occupational Therapists",
      "Nutritionists / Dieticians",
      "Fitness Trainers / Gyms",
      "Yoga / Meditation Experts",
      "Mental Health Coaches / Psychologists",
      "Other",
    ],
  },
  {
    category: "Education, Coaching & Training",
    subcategories: [
      "Academic Institutes / Schools",
      "EdTech Startups",
      "Skill Development Centers",
      "Life / Business / Career Coaches",
      "Corporate Trainers",
      "Language Trainers",
      "Study Abroad Consultants",
      "Other",
    ],
  },
  {
    category: "Real Estate & Construction",
    subcategories: [
      "Real Estate Agents",
      "Builders / Developers",
      "Interior Designers",
      "Architects",
      "Vastu Consultants",
      "Civil Contractors / PMC",
      "Building Material Suppliers",
      "Other",
    ],
  },
  {
    category: "Manufacturing & Industrial Services",
    subcategories: [
      "Product Manufacturers",
      "OEM / B2B Component Suppliers",
      "Industrial Automation / Robotics",
      "EPC / MEP Consultants",
      "Chemical / Pharma Manufacturing",
      "Packaging Solutions",
      "Safety & Fire Equipment Suppliers",
      "Other",
    ],
  },
  {
    category: "Retail, E-commerce & Distribution",
    subcategories: [
      "FMCG Distributors / Traders",
      "Boutique Stores / Apparel / Lifestyle",
      "Grocery / Essentials Suppliers",
      "Online Marketplace Sellers",
      "D2C Brand Owners",
      "Franchise Consultants",
      "Other",
    ],
  },
  {
    category: "Food, Beverages & Hospitality",
    subcategories: [
      "Restaurant / Café Owners",
      "Cloud Kitchen Owners",
      "Packaged Food Businesses",
      "Catering Services",
      "Food Tech Startups",
      "Beverage Distributors",
      "Hotel / Resort Owners",
      "Other",
    ],
  },
  {
    category: "Travel & Tourism",
    subcategories: [
      "Travel Agents / Tour Operators",
      "Visa & Documentation Experts",
      "Travel Bloggers / Experience Curators",
      "Corporate Travel Planners",
      "Other",
    ],
  },
  {
    category: "Logistics, Supply Chain & Mobility",
    subcategories: [
      "Courier / Logistics Providers",
      "Packers & Movers",
      "Supply Chain Consultants",
      "EV Mobility Startups",
      "Transportation Aggregators",
      "Other",
    ],
  },
  {
    category: "Fashion, Lifestyle & Personal Care",
    subcategories: [
      "Fashion Designers / Boutiques",
      "Stylists / Personal Shoppers",
      "Salon / Spa Owners",
      "Cosmetic Product Dealers",
      "Jewellery Designers / Traders",
      "Other",
    ],
  },
  {
    category: "Art, Culture & Creative Services",
    subcategories: [
      "Artists / Painters / Sculptors",
      "Musicians / Performers",
      "Voice Over Artists",
      "Authors / Writers",
      "Art Curators / Art Dealers",
      "Other",
    ],
  },
  {
    category: "Green, Eco & Sustainable Businesses",
    subcategories: [
      "Organic / Natural Products",
      "Sustainability Consultants",
      "Eco-Packaging / Green Tech",
      "Waste Management / Recycling",
      "Renewable Energy Solutions",
      "Other",
    ],
  },
];

export default categories;

