name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_SSH_KEY" | tr -d '\r' | sed 's/\\n/\n/g' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}

      - name: Deploy to EC2
        run: |
          echo "Connecting to EC2..."
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << EOF
            echo "✅ Logged into EC2"
            cd $EC2_PATH
            echo "📦 Pulling latest code..."
            git pull origin main
            echo "📦 Installing dependencies..."
            npm install
            echo "🚀 Restarting app with PM2..."
            pm2 restart bizcivitas-backend || pm2 start src/index.js --name bizcivitas-backend
            echo "✅ Deployment complete!"
          EOF
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_PATH: ${{ secrets.EC2_PATH }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
